package pl.gdgrzeszow.k8s;

import com.jmethods.catatumbo.DatastoreKey;
import com.jmethods.catatumbo.Entity;
import com.jmethods.catatumbo.Identifier;
import com.jmethods.catatumbo.Key;
import java.time.OffsetDateTime;

@Entity(kind = "User")
public class SampleEntity {

    @Key
    private DatastoreKey key;
    @Identifier(autoGenerated = true)
    private String id;
    private String email;
    private OffsetDateTime offsetDateTime = OffsetDateTime.now();

    @Override
    public String toString() {
        return "{\"SampleEntity\":{"
            + "                        \"key\":\"" + key + "\""
            + ",                         \"id\":\"" + id + "\""
            + ",                         \"email\":\"" + email + "\""
            + ",                         \"offsetDateTime\":\"" + offsetDateTime + "\""
            + "}}";
    }

    public DatastoreKey getKey() {
        return key;
    }

    public void setKey(DatastoreKey key) {
        this.key = key;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}

